# context file for the web scraper and LLM

# the config settings for the news scraper
news:

  # The string to use to define what to search for:
  TOPIC: 'drone OR quadcopter OR hexacopter'

  # The language code to use
  LANGUAGE: 'en'

  # The country code to use
  COUNTRY: 'US'

  # How far back in time to look for articles EXAMPLE: 1h, 7d, 1m, 1y
  LOOKBACK: '1h'

# config settings for the LLM analyzer
llm:

  # Which model to use
  ID: 'llama3.2'

  # The context for what the model is supposed to do
  CONTEXT: 'Analyze the following news article and decide if it is about a drone incident or not.  An incident is where a drone or UAV has done an illegal act, such as flying where it is not supposed to or harming people and property.  Return a JSON object with the results. The JSON object should contain the following fields:  "isIncident" (boolean), "isUnique" (boolean), and "location" (string).  The "isIncident" field should be true if the article is about a drone incident and false otherwise.  The "isUnique" field should be true if the news story is not like any of the incidents inside the history list.  If a news story is about the same event, it is not unique and should be false.  If a news story is about a incident not in the history list, then "isUnique" should be true.  The "location" field should be a string that represents the location of the story in a City, State format.  If the location is not in the United States, set the location to City, Country. Only return these fields.  Do not return anything other than the JSON object.'